# Generated by Django 5.2.13 on 2026-04-19 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Lab Staff')], default='staff', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('assigned_lab', models.ForeignKey(blank=True, help_text='For staff: which lab they manage', null=True, on_delete=django.db.models.deletion.SET_NULL, to='labs.lab')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
