# Generated by Django 5.2.13 on 2026-04-26 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_add_department_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labs.devicecategory'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('working', 'Working'), ('maintenance', 'Maintenance'), ('trash', 'Trash')], default='working', max_length=20),
        ),
    ]
