# Generated by Django 5.2.13 on 2026-05-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0005_add_device_ip_config_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='os_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='device',
            name='software_details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
